@echo off
echo Restarting BSwisdom site server...

echo Stopping any running Node.js processes...
taskkill /f /im node.exe >nul 2>&1

echo Cleaning node_modules...
rmdir /s /q node_modules

echo Reinstalling dependencies...
npm install

echo Starting development server...
npm run dev